Feature/Miami-15: Добавить страницу пользователя, вынести пару стилей…
oduvankenobi/08-miami pull request #15
Opened 2021-10-01 13:37 UTC by Nilfan

… в UI components

2021-10-01 15:43 UTC, oduvankenobi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать страницу пользователя](https://trello.com/c/lAMPVyCe/15-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F)

2021-10-04 12:30 UTC, alexmented commented on src/pages/UserPage/UserPage.tsx
> +    const history = useHistory();
Оборачивать надо в withRouter

2021-10-04 12:34 UTC, alexmented commented on src/components/UserInfo/styled.ts
> +export const TableWrapper = styled.table`
Там же в ui есть Table для стилизации как раз

2021-10-07 19:09 UTC, Nilfan commented on src/components/UserInfo/styled.ts
> +export const TableWrapper = styled.table`
Мне не подходят те стили

2021-10-07 19:16 UTC, Nilfan commented on ui/components/BackButton/index.ts
> +import { BackButton } from './BackButton';
Хороший поинт, поправил

2021-10-07 19:16 UTC, Nilfan commented on src/pages/UserPage/index.ts
> +import { UserPage } from './UserPage';
Хороший поинт, поправил

2021-10-09 12:46 UTC, oduvankenobi commented on src/components/UserInfo/ChangeUserInfoTable.tsx
> +    const formRef = React.createRef<HTMLFormElement>();
эти рефы можно убрать, потому что мы будем формик юзать

2021-10-09 12:46 UTC, oduvankenobi commented on src/components/UserInfo/ChangeUserPasswordTable.tsx
> +    const formRef = React.createRef<HTMLFormElement>();
этот тоже можно удалить

2021-10-09 12:47 UTC, oduvankenobi commented on ui/components/Title/index.ts
> +import { Title } from './Title';
здесь сделай, пожалуйста, просто импорт сразу всего, как сделал до этого :)

2021-10-09 13:36 UTC, Nilfan commented on src/components/UserInfo/ChangeUserInfoTable.tsx
> +    const formRef = React.createRef<HTMLFormElement>();
Убрал

2021-10-10 09:55 UTC, alexmented commented on src/components/UserInfo/styled.ts
> +export const TableWrapper = styled.table`
Ну мне каж над доработать тогда таблицу в ui, чтобы она универсальная была, а то смысла тогда в ней нет, если она везде своя будет

2021-10-10 09:58 UTC, alexmented requested changes
Формик над заюзать будет

2021-10-10 12:22 UTC, Nilfan commented
Думаю подрубить формик вместе с api

2021-10-10 12:24 UTC, Nilfan commented on src/components/UserInfo/styled.ts
> +export const TableWrapper = styled.table`
++

2021-10-10 12:56 UTC, Nilfan commented on ui/components/Title/index.ts
> +import { Title } from './Title';
Сделал)

2021-10-13 08:23 UTC, merged