Feature/miami 5 Страница leaderboard
oduvankenobi/08-miami pull request #5
Opened 2021-09-23 18:01 UTC by alexmented

Добавлена страница leaderborard и добавлен Redirect на стартовую страницу

2021-09-23 18:03 UTC, alexmented commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сделать страницу лидерборда](https://trello.com/c/xx6BwHk8/5-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83-%D0%BB%D0%B8%D0%B4%D0%B5%D1%80%D0%B1%D0%BE%D1%80%D0%B4%D0%B0)

2021-09-24 06:56 UTC, oduvankenobi requested changes

2021-09-24 06:56 UTC, oduvankenobi commented on src/components/App.tsx
>                          </Route>
строчки 18-20, наверное, уже можно удалить 👀

2021-09-24 07:03 UTC, Nilfan commented on src/components/App.tsx
>                          </Route>
Я думаю, example можно вынести отдельным Route'ом, а в корень положить React.Segment. Пока мы ещё клепаем части app, до которых не добраться (Game), такая страница будет полезна

2021-09-24 07:05 UTC, oduvankenobi commented on src/components/App.tsx
>                          </Route>
немного не поняла, зачем страница экзампла, если у нас пока страница лидерборда корнвая получается

2021-09-24 07:18 UTC, Nilfan commented on src/components/App.tsx
>                          </Route>
Не, погоди)

"/" - <Example>
"/leaderboard" - <Leaderboard>
Такое состояние нашего роутинга на данный момент в этом PR.

 А моё предложение - сделать так:
"/" - () => <></>
"/example" - <Example>
"/leaderboard" - <Leaderboard>

2021-09-24 07:26 UTC, alexmented commented on src/components/App.tsx
>                          </Route>
Я оставил Example на главной, просто, чтобы она не была пока пустой. Сейчас главную сверстаем и заменим. Отдельно выносить example в роут мне каж не надо, потому что это был пример оформления кнопок в дизайн системе, поэтому его долго держать особо смысла нет

2021-09-24 07:30 UTC, Nilfan submitted a review, later dismissed

2021-09-24 07:30 UTC, Nilfan commented
Тогда мне ок

2021-09-24 07:33 UTC, oduvankenobi commented on src/components/App.tsx
>                          </Route>
ну я просто про то и говорю, что мы, вроде, договорились вчера тестовое/примеры в основном коде не держать
а кнопочки и таблицы (да и вообще использование стайлд компонент) у тебя уже есть в табличке лидерборда
лидерборд всё равно редиректит на корень, поэтому я и говорю, что лидерборд, фактически, корневой сейчас)

2021-09-24 07:35 UTC, oduvankenobi commented on src/components/App.tsx
>                          </Route>
ну ок, если вам принципиально не удалять экзампл, я апрувну)

2021-09-24 07:35 UTC, oduvankenobi approved these changes

2021-09-24 07:38 UTC, alexmented commented on src/components/App.tsx
>                          </Route>
leaderboard не редиректит на корень, на корень редирктит все, кроме "/" и "/leaderboard", если левый url ввести типа /bad - то редирект на /

2021-09-24 08:11 UTC, oduvankenobi commented on src/components/App.tsx
>                          </Route>
ok

2021-09-24 09:24 UTC, oduvankenobi approved these changes

2021-09-24 09:49 UTC, Nilfan approved these changes

2021-09-24 15:19 UTC, kotosha-real approved these changes
🕵🏻‍♂️
Есть аппрув, но погляди комменты, кое-что хочется поправить

2021-09-24 15:19 UTC, kotosha-real commented on src/components/Leaderboard/TableBody/styled.ts
> +    &:first-child {
❗️
Это разные сущности, давай визуально разделим
```suggestion
    height: 50px;
    
    &:first-child {
```

2021-09-24 15:19 UTC, kotosha-real commented on src/components/Leaderboard/TableBody/styled.ts
> +        border-top-left-radius: 10px;
🧐
Их можно смержить в одно правило, на твоё усмотрение)

2021-09-24 15:19 UTC, kotosha-real commented on src/components/Leaderboard/TableHead/styled.ts
> +    &:first-child {
❗️
Аналогично первому комменту

2021-09-24 15:19 UTC, kotosha-real commented on src/components/Leaderboard/fakeData.ts
> +        points: 10,
🧐
`points` вразброс, но для моков ок. Названия полей можно, кстати, наперёд стащить из апи лидерборда

2021-09-24 15:19 UTC, kotosha-real commented on src/components/Leaderboard/styled.ts
> +import { ITheme } from '../../../ui/themes';
❗️
Очень хочется алиасы, чтобы заборчиков не было

2021-09-24 16:16 UTC, oduvankenobi commented on src/components/Leaderboard/styled.ts
> +import { ITheme } from '../../../ui/themes';
завела на себя таску, так как вебпак — моя зона ответственности

2021-09-25 08:06 UTC, merged